AllCops:
  TargetRubyVersion: 2.4

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Lint/DisjunctiveAssignmentInConstructor:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 90

Metrics/ClassLength:
  Max: 150
